### ISSUE TITLE
Fix Flutter Workflow Cache Restore

### ISSUE THREAD

**Issue by ChuufMaster** [COS301-SE-2024/BeakPeek#65]
In [flutter workflow](https://github.com/COS301-SE-2024/BeakPeek/blob/4171e2edce0902910ce09b1d7fa3be32db2de083/.github/workflows/flutter.yml)

It might have something to do with this block of code:
```yml
name: Cache Flutter dependancies
        uses: actions/cache@v3
        with:
          path: |
            ~./.pub-cache
            ~./.flutter
          keys: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-
# ----------^^^^^^^^^^^^^^^^^^^^^--------------------
```
